image:
  repository: ghcr.io/trezm/superposition-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 443

auth:
  username: ""
  password: ""
  gatewaySecret: ""

tls:
  certSecret: ""

ingress:
  enabled: false
  className: public
  clusterIssuer: letsencrypt
  host: ""
  annotations: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
